const SECMARKET_DATA = {
  categories: [
    ["Игровая валюта", "USDT-цены, быстрая выдача", "VC"],
    ["Аккаунты", "Steam, Roblox, Telegram", "AC"],
    ["Ключи", "Игры, софт, подписки", "KY"],
    ["Подписки", "Сервисы и приложения", "SB"],
    ["Пополнение", "Балансы и донат", "TP"],
    ["Предметы", "Скины, вещи, инвентарь", "IT"],
    ["Услуги", "Буст, прокачка, помощь", "SV"],
    ["Скины", "Valorant, CS, Fortnite", "SK"],
    ["Софт", "Цифровые товары", "SW"],
    ["Другое", "Нишевые предложения", "OT"],
  ],
  quickLinks: ["Roblox", "Steam", "Telegram", "Discord", "Minecraft", "Brawl Stars", "Valorant", "PUBG", "PlayStation", "Xbox"],
  subcategories: {
    roblox: ["Robux", "Аккаунты", "Предметы", "Услуги", "Game Pass", "VIP-сервера", "Группы", "Буст"],
    steam: ["Gift Card", "Ключи", "Аккаунты", "Скины", "Баланс"],
    telegram: ["Premium", "Аккаунты", "Номера", "Каналы", "Боты"],
    discord: ["Nitro", "Серверы", "Бусты", "Аккаунты", "Боты"],
    minecraft: ["Аккаунты", "Ключи", "Сервера", "Донат", "Услуги"],
  },
  categoryPages: {
    roblox: {
      title: "Roblox",
      description: "Roblox-раздел для Robux, аккаунтов, предметов, Game Pass и услуг с понятной выдачей и защитой сделки.",
      seo: "Покупайте Robux, аккаунты Roblox и игровые услуги за USDT. В карточках видны остатки, рейтинг продавца, тип выдачи и условия проверки после покупки.",
      faq: ["Как быстро приходят Robux: зависит от типа товара и условий продавца.", "Что проверять: никнейм, регион, срок выдачи и гарантию.", "Когда открывать спор: если товар не выдан или не соответствует описанию."],
    },
    steam: {
      title: "Steam",
      description: "Ключи, Gift Card, аккаунты и скины Steam с фиксацией суммы, сети оплаты и истории заказа.",
      seo: "Steam-товары в SecMarket удобно фильтровать по цене, рейтингу и типу выдачи. Для ключей и подарочных карт подходит автовыдача после подтверждений сети.",
      faq: ["Проверяйте регион ключа до оплаты.", "Gift Card выдаются кодом или инструкцией.", "Если код не активируется, приложите скриншот в спор."],
    },
    telegram: {
      title: "Telegram",
      description: "Telegram Premium, аккаунты, номера, каналы и боты с ручной выдачей через чат заказа.",
      seo: "В Telegram-разделе важны срок передачи, правила восстановления и подтверждение владения. Поддержка видит связанный заказ, платеж и переписку.",
      faq: ["Premium обычно выдается подарком или инструкцией.", "Для аккаунтов уточняйте 2FA и восстановление.", "Все данные передачи держите внутри чата заказа."],
    },
    discord: {
      title: "Discord",
      description: "Discord Nitro, бусты серверов, аккаунты и услуги для сообществ с прозрачным статусом выполнения.",
      seo: "Discord-товары могут быть ручными или автоматическими. Перед покупкой проверьте срок действия Nitro, регион и правила продавца.",
      faq: ["Nitro может выдаваться ссылкой или кодом.", "Для бустов указывайте корректный сервер.", "Не подтверждайте заказ до проверки активации."],
    },
    minecraft: {
      title: "Minecraft",
      description: "Minecraft Java, ключи, серверный донат и услуги с гарантией, проверкой региона и спором по заказу.",
      seo: "Minecraft-раздел собирает аккаунты, ключи и серверные услуги. В MVP продавец указывает гарантию, срок выполнения и тип выдачи.",
      faq: ["Проверяйте тип аккаунта и почту.", "Для серверного доната указывайте никнейм.", "При проблеме приложите скрин входа или покупки."],
    },
  },
  products: [
    { id: 12345, title: "Robux 10 000, выдача 5 минут", cat: "Roblox", price: 84.9, usd: 84.9, seller: "PixelTrade", rating: 4.98, sales: 2381, type: "Автовыдача", stock: 48, colors: ["#2a6f97", "#47D651"], mark: "RB" },
    { id: 22341, title: "Steam Gift Card 50 USDT", cat: "Steam", price: 50, usd: 50, seller: "KeyDock", rating: 4.92, sales: 1840, type: "Автовыдача", stock: 120, colors: ["#223556", "#67aaf9"], mark: "ST" },
    { id: 33412, title: "Telegram Premium 12 месяцев", cat: "Telegram", price: 31.5, usd: 31.5, seller: "SubLine", rating: 4.88, sales: 902, type: "Ручная", stock: 16, colors: ["#1f6f8b", "#e85d87"], mark: "TG" },
    { id: 44510, title: "Minecraft Java аккаунт", cat: "Minecraft", price: 12.8, usd: 12.8, seller: "MineVault", rating: 4.81, sales: 671, type: "Автовыдача", stock: 37, colors: ["#335c34", "#f4bd4f"], mark: "MC" },
    { id: 55118, title: "Valorant VP, регион EU", cat: "Valorant", price: 22.4, usd: 22.4, seller: "AimShop", rating: 4.96, sales: 1120, type: "Ручная", stock: 23, colors: ["#4a1f2f", "#ff6b6b"], mark: "VP" },
    { id: 66209, title: "Discord Nitro 1 месяц", cat: "Discord", price: 7.2, usd: 7.2, seller: "NitroBay", rating: 4.76, sales: 504, type: "Автовыдача", stock: 89, colors: ["#303c88", "#7bd88f"], mark: "DN" },
    { id: 77102, title: "PUBG UC, быстрая отправка", cat: "PUBG", price: 18.6, usd: 18.6, seller: "DropZone", rating: 4.9, sales: 1320, type: "Ручная", stock: 41, colors: ["#493819", "#f4bd4f"], mark: "UC" },
    { id: 88444, title: "PlayStation Plus Deluxe", cat: "PlayStation", price: 39.9, usd: 39.9, seller: "ConsoleHub", rating: 4.84, sales: 774, type: "Автовыдача", stock: 14, colors: ["#143c68", "#67aaf9"], mark: "PS" },
  ],
  sellers: [
    ["PixelTrade", "4.98", "12 840", "USDT TRC20"],
    ["KeyDock", "4.92", "9 310", "USDT TON"],
    ["SubLine", "4.88", "4 704", "USDT BEP20"],
    ["AimShop", "4.96", "7 122", "USDT TRC20"],
  ],
  demoUsers: [
    { id: "usr-buyer", role: "buyer", name: "Artem", email: "buyer@example.com", telegram: "@buyer", status: "active" },
    { id: "usr-seller", role: "seller", name: "PixelTrade", email: "seller@example.com", telegram: "@pixeltrade", status: "active" },
    { id: "usr-admin", role: "admin", name: "SupportOne", email: "support@example.com", telegram: "@support", status: "active" },
  ],
  demoOrders: [
    { id: 12345, product: "Robux 10 000", seller: "PixelTrade", buyer: "Artem", amount: 88.3, payment: "Оплачено", order: "Ожидает подтверждения", delivery: "Автовыдача" },
    { id: 22341, product: "Steam Gift Card", seller: "KeyDock", buyer: "Artem", amount: 50, payment: "Оплачено", order: "Завершен", delivery: "Автовыдача" },
    { id: 33412, product: "Telegram Premium", seller: "SubLine", buyer: "Artem", amount: 31.5, payment: "Ожидает подтверждений", order: "В работе", delivery: "Ручная" },
    { id: 77102, product: "PUBG UC", seller: "DropZone", buyer: "Artem", amount: 18.6, payment: "Оплачено", order: "Спор", delivery: "Ручная" },
  ],
  demoPayments: [
    { id: "pay-12345", order: 12345, amount: 88.3, coin: "USDT", network: "TRC20", status: "Оплачено", confirmations: "3/3", tx: "tx_trc20_9a2" },
    { id: "pay-22341", order: 22341, amount: 50, coin: "USDT", network: "TON", status: "Оплачено", confirmations: "1/1", tx: "tx_ton_17b" },
    { id: "pay-33412", order: 33412, amount: 31.5, coin: "USDT", network: "BEP20", status: "Ожидает подтверждений", confirmations: "8/12", tx: "tx_bep20_42c" },
  ],
  demoTickets: [
    { id: "SUP-104", topic: "Проблема с оплатой", order: 12345, status: "Открыт" },
    { id: "SUP-097", topic: "Вопрос по заказу", order: 33412, status: "Ждет ответа" },
    { id: "SUP-081", topic: "Возврат", order: 77102, status: "Закрыт" },
  ],
  demoDisputes: [
    { id: 123, order: 12345, buyer: "Artem", seller: "PixelTrade", reason: "Товар не работает", status: "Ожидает поддержки", refund: "частичный возврат 40%", payment: "pay-12345" },
    { id: 44, order: 12345, buyer: "Artem", seller: "PixelTrade", reason: "Товар не выдан", status: "Ожидает поддержки", refund: "решение не принято", payment: "pay-12345" },
    { id: 39, order: 77102, buyer: "Artem", seller: "DropZone", reason: "Запрошены данные", status: "На проверке", refund: "возможен полный возврат", payment: "pay-77102" },
  ],
  demoWithdrawals: [
    { id: "WD-120", seller: "PixelTrade", amount: 500, network: "TRC20", address: "TQ9...Lm2", status: "На проверке", tx: "ожидается", risk: "адрес новый" },
    { id: "WD-108", seller: "KeyDock", amount: 300, network: "TON", address: "UQ7...Ton", status: "Выполнен", tx: "tx_ton_out_108", risk: "низкий" },
    { id: "WD-099", seller: "SubLine", amount: 150, network: "BEP20", address: "0x91...b20", status: "Отклонен", tx: "не отправлен", risk: "адрес не совпал" },
  ],
  moderationQueue: [
    { id: "MOD-201", type: "Товар", target: "Robux 10 000, выдача 5 минут", owner: "PixelTrade", status: "Новая проверка", reason: "изменена цена и автовыдача" },
    { id: "MOD-188", type: "Жалоба", target: "Steam Gift Card 50 USDT", owner: "KeyDock", status: "Нужен ответ", reason: "покупатель сообщил о регионе ключа" },
    { id: "MOD-174", type: "Отзыв", target: "Telegram Premium 12 месяцев", owner: "SubLine", status: "На модерации", reason: "есть вложение со скриншотом" },
    { id: "MOD-162", type: "Продавец", target: "RiskyShop", owner: "RiskyShop", status: "Ограничен", reason: "высокий процент споров" },
  ],
  dataModels: [
    ["User", "роль, email, Telegram, 2FA, статусы безопасности"],
    ["Product", "категория, продавец, цена, остатки, тип выдачи, модерация"],
    ["Order", "покупатель, продавец, товар, escrow, статусы выполнения"],
    ["Payment", "монета, сеть, адрес, tx hash, подтверждения, связанный заказ"],
    ["Chat", "сообщения, файлы, системные события, контекст заказа"],
    ["Dispute", "причина, доказательства, решение, возврат, заморозка средств"],
    ["Withdrawal", "продавец, адрес, сеть, сумма, tx hash, история статусов"],
  ],
  apiEndpoints: [
    ["GET /api/products", "каталог, фильтры, категории"],
    ["POST /api/products", "создание товара продавцом"],
    ["PATCH /api/products/:id", "редактирование и модерация товара"],
    ["POST /api/orders", "создание заказа и escrow"],
    ["GET /api/orders/:id", "детальная страница заказа"],
    ["POST /api/payments", "создание crypto invoice"],
    ["PATCH /api/payments/:id/status", "ручная или автоматическая смена статуса"],
    ["POST /api/disputes", "открытие спора"],
    ["PATCH /api/disputes/:id/decision", "решение поддержки и возврат"],
    ["POST /api/support/tickets", "создание тикета"],
    ["PATCH /api/withdrawals/:id", "подтверждение выплаты и tx hash"],
    ["GET /api/admin/moderation", "очередь товаров, жалоб, отзывов и продавцов"],
  ],
  infoPages: {
    "/terms": ["Пользовательское соглашение", "Правила безопасной сделки, покупки цифровых товаров, статусы заказов и ответственность сторон."],
    "/privacy": ["Политика конфиденциальности", "Минимальный сбор данных для заказов, чатов, платежей и поддержки."],
    "/refund-policy": ["Политика возвратов", "Возвраты рассматриваются через спор, с учетом статуса выдачи и подтверждения оплаты."],
    "/seller-rules": ["Правила продавцов", "Точные описания, честные сроки, рабочие товары, запрет выдачи повторно проданных данных."],
    "/buyer-rules": ["Правила покупателей", "Оплата только выбранной сетью, проверка товара после получения, корректное ведение спора."],
    "/crypto-payment-guide": ["Инструкция по оплате криптой", "Выберите USDT TRC20, TON или BEP20, отправьте точную сумму и дождитесь подтверждений."],
    "/fees": ["Комиссии", "Платформа удерживает комиссию после завершения заказа, сетевые комиссии оплачиваются отправителем."],
    "/contacts": ["Контакты", "Поддержка работает через тикеты, спор по заказу и системный чат."],
    "/faq": ["FAQ", "Ответы по оплате, выдаче, спорам, возвратам, статусам и ручным выплатам."],
    "/status-map": ["Карта статусов", "Все основные статусы оплаты, заказов, средств продавца и выплат в MVP."],
    "/backend-structure": ["Backend-ready структура", "Демо-данные уже сгруппированы вокруг будущих сущностей: пользователи, товары, заказы, платежи, чаты, споры и выплаты."],
  },
  routeLinks: [
    ["/catalog", "Каталог"],
    ["/seller/products/create", "Продать"],
    ["/orders/12345", "Заказы"],
    ["/chats", "Чаты"],
    ["/notifications", "Уведомления"],
    ["/account", "Профиль"],
  ],
  accountLinks: [
    ["Профиль", "/account"],
    ["Мои заказы", "/account/orders"],
    ["Избранное", "/account/favorites"],
    ["Чаты", "/chats"],
    ["Споры", "/disputes"],
    ["Отзывы", "/account/reviews"],
    ["Настройки", "/account/settings"],
    ["Безопасность", "/account/security"],
    ["История оплат", "/account/payments"],
  ],
  sellerLinks: [
    ["Обзор", "/seller"],
    ["Профиль", "/seller/profile"],
    ["Мои товары", "/seller/products"],
    ["Создать товар", "/seller/products/create"],
    ["Заказы", "/seller/orders"],
    ["Чаты", "/chats"],
    ["Финансы", "/seller/finance"],
    ["Выплаты", "/seller/withdraw"],
    ["Отзывы", "/seller/reviews"],
    ["Настройки", "/seller/settings"],
    ["Правила", "/seller-rules"],
  ],
  adminLinks: [
    ["Дашборд", "/admin"],
    ["Пользователи", "/admin/users"],
    ["Продавцы", "/admin/sellers"],
    ["Товары", "/admin/products"],
    ["Заказы", "/admin/orders"],
    ["Платежи", "/admin/payments"],
    ["Выплаты", "/admin/payouts"],
    ["Споры", "/admin/disputes"],
    ["Тикеты", "/admin/tickets"],
    ["Категории", "/admin/categories"],
    ["Промокоды", "/admin/promocodes"],
    ["Комиссии", "/admin/fees"],
    ["Крипто-платежи", "/admin/crypto"],
    ["Модерация", "/admin/moderation"],
  ],
};

window.SECMARKET_DATA = SECMARKET_DATA;
